id: P009420
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 19:37:53.052424
source_metadata:
  id: bdr:W3CN507
  title: གླེགས་བམ་རིན་པོ་ཆེ་དགོས་འདོད་ཀུན་འབྱུང་།
  author: ''
  volumes:
    186dcd65cb4d416383656f7ce089bc09:
      image_group_id: I3CN4550
      title: ''
      volume_number: 1
      total_pages: 1186
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
