id: IA35B199A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T23:18:58+00:00'
last_modified: '2022-06-08T10:54:42.471637+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN507
  title: གླེགས་བམ་རིན་པོ་ཆེ་དགོས་འདོད་ཀུན་འབྱུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B81B:
      image_group_id: I3CN4550
      title: ''
      total_pages: 1186
      order: 1
      base_file: B81B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
